formspree_form_id: formspree_form_id
name: $ 21 coders
title: $ 21 coders | 21st century skills
description: $ 21 Coders — o‘zbek dasturchilar jamoasi bo‘lib, zamonaviy
  texnologiyalarni o‘rganish va o‘rgatish uchun yaratilgan platforma.
tags:
  - ta'lim
  - dasturlash
  - IT kurslar
  - onlayn ta'lim
  - web dasturlash
  - jekyll
  - netlify
  - blog
  - ta'lim platformasi
  - uzbek developers
  - html
  - css
  - javascript
  - open source
  - coding community
  - 21 coders
  - 21-asr ko‘nikmalari
  - raqamli savodxonlik
  - talabalar uchun
  - yosh dasturchilar
  - portfolio
  - ta'lim shabloni
  - developer blog
show_hero: true
paginate: 6
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: jks21stcenturyskills@gmail.com
disqus_username: disqus_username
